version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=beer_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: