version: '3'
services:
  webcrawler:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_NAME=crawler_db
      - DB_USER=crawler_user
      - DB_PASSWORD=crawler_password
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=crawler_db
      - POSTGRES_USER=crawler_user
      - POSTGRES_PASSWORD=crawler_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
