name: Scrapy Crawl  
  
on:  
  push:  
    branches:  
      - main  # Replace with your main branch name  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v2  
  
    - name: Set up Python  
      uses: actions/setup-python@v2  
      with:  
        python-version: 3.8  
  
    - name: Install dependencies  
      run: |  
        python -m pip install --upgrade pip  
        pip install scrapy  
  #Wenn Projekt gestartet dann Crawl start
    #- name: Run Scrapy crawl  
      #run: |  
      #  cd path/to/your/scrapy/project  # Replace with the path to your Scrapy project  
      #  scrapy crawl your_spider_name  # Replace with the name of your Scrapy spider  
